//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbrus_region.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sostav_uslugi
    {
        public int id { get; set; }
        public int ID_zakaza { get; set; }
        public int ID_usluga { get; set; }
    
        public virtual Uslugi Uslugi { get; set; }
        public virtual Zakaz Zakaz { get; set; }
    }
}
