//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbrus_region.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uslugi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uslugi()
        {
            this.Sostav_uslugi = new HashSet<Sostav_uslugi>();
        }
    
        public int ID_uslugi { get; set; }
        public string usluga { get; set; }
        public string cod_uslugi { get; set; }
        public int stoimost_uslugi { get; set; }
        public string UslugaImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sostav_uslugi> Sostav_uslugi { get; set; }

        public string Background
        {
            get
            {
                if (this.stoimost_uslugi < 500)
                    return "#7fff00";
                        return "#fff";
            }
        }

        public string ImgPath
        {
            get
            {
                var path = "pack://application:,,,/Resources/" + this.UslugaImage;
                return path;
            }
        }

    }
}
