//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elbrus_region.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zakaz()
        {
            this.Sostav_uslugi = new HashSet<Sostav_uslugi>();
        }
    
        public int ID_zakaz { get; set; }
        public int code_zakaz { get; set; }
        public System.DateTime data_zakaza { get; set; }
        public System.TimeSpan time_zakaza { get; set; }
        public int code_client { get; set; }
        public Nullable<int> status_zakaza { get; set; }
        public Nullable<System.DateTime> data_zakr { get; set; }
        public int time { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sostav_uslugi> Sostav_uslugi { get; set; }
        public virtual Status_zakaz Status_zakaz { get; set; }
    }
}
